# Main Link
# https://football-data.co.uk/englandm.php


# Project 1:
**Single URL Theke Data Read**

In [36]:
import pandas as pd

In [37]:
df = pd.read_csv('https://football-data.co.uk/mmz4281/1516/E0.csv')

In [38]:
df

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,PSCH,PSCD,PSCA
0,E0,08/08/2015,Bournemouth,Aston Villa,0,1,A,0,0,D,...,1.79,26,-0.50,1.98,1.93,1.99,1.92,1.82,3.88,4.70
1,E0,08/08/2015,Chelsea,Swansea,2,2,D,2,1,H,...,1.99,27,-1.50,2.24,2.16,1.80,1.73,1.37,5.04,10.88
2,E0,08/08/2015,Everton,Watford,2,2,D,0,1,A,...,1.96,26,-1.00,2.28,2.18,1.76,1.71,1.75,3.76,5.44
3,E0,08/08/2015,Leicester,Sunderland,4,2,H,3,0,H,...,1.67,26,-0.50,2.00,1.95,1.96,1.90,1.79,3.74,5.10
4,E0,08/08/2015,Man United,Tottenham,1,0,H,1,0,H,...,2.01,26,-1.00,2.20,2.09,1.82,1.78,1.64,4.07,6.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,15/05/2016,Stoke,West Ham,2,1,H,0,1,A,...,2.27,30,0.25,2.11,2.03,1.87,1.83,3.05,4.00,2.26
376,E0,15/05/2016,Swansea,Man City,1,1,D,1,1,D,...,2.45,31,1.00,2.14,2.05,1.85,1.81,7.05,5.00,1.47
377,E0,15/05/2016,Watford,Sunderland,2,2,D,0,1,A,...,2.10,29,-0.50,2.06,2.01,1.91,1.85,1.64,4.52,5.27
378,E0,15/05/2016,West Brom,Liverpool,1,1,D,1,1,D,...,2.09,30,-0.25,2.10,2.05,1.86,1.81,2.61,3.75,2.70
379,E0,17/05/2016,Man United,Bournemouth,3,1,H,1,0,H,...,2.20,29,-0.75,1.88,1.84,2.08,2.02,1.50,4.60,7.03

In [39]:
df.head(10)

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,PSCH,PSCD,PSCA
0,E0,08/08/2015,Bournemouth,Aston Villa,0,1,A,0,0,D,...,1.79,26,-0.50,1.98,1.93,1.99,1.92,1.82,3.88,4.70
1,E0,08/08/2015,Chelsea,Swansea,2,2,D,2,1,H,...,1.99,27,-1.50,2.24,2.16,1.80,1.73,1.37,5.04,10.88
2,E0,08/08/2015,Everton,Watford,2,2,D,0,1,A,...,1.96,26,-1.00,2.28,2.18,1.76,1.71,1.75,3.76,5.44
3,E0,08/08/2015,Leicester,Sunderland,4,2,H,3,0,H,...,1.67,26,-0.50,2.00,1.95,1.96,1.90,1.79,3.74,5.10
4,E0,08/08/2015,Man United,Tottenham,1,0,H,1,0,H,...,2.01,26,-1.00,2.20,2.09,1.82,1.78,1.64,4.07,6.04
5,E0,08/08/2015,Norwich,Crystal Palace,1,3,A,0,1,A,...,1.67,27,0.00,1.83,1.78,2.17,2.08,2.46,3.39,3.14
6,E0,09/08/2015,Arsenal,West Ham,0,2,A,0,1,A,...,2.22,27,-1.50,1.96,1.89,2.06,1.96,1.24,6.75,15.00
7,E0,09/08/2015,Newcastle,Southampton,2,2,D,1,1,D,...,1.70,27,0.00,2.06,1.98,1.92,1.87,3.09,3.28,2.55
8,E0,09/08/2015,Stoke,Liverpool,0,1,A,0,0,D,...,1.75,26,0.25,2.00,1.95,1.96,1.91,3.89,3.51,2.09
9,E0,10/08/2015,West Brom,Man City,0,3,A,0,2,A,...,2.04,26,1.00,1.78,1.74,2.24,2.14,6.46,4.08,1.61

In [40]:
df.tail(10)

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,PSCH,PSCD,PSCA
370,E0,15/05/2016,Arsenal,Aston Villa,4,0,H,1,0,H,...,3.08,30,-2.25,1.96,1.91,1.99,1.94,1.12,12.03,23.60
371,E0,15/05/2016,Chelsea,Leicester,1,1,D,0,0,D,...,2.25,30,-0.25,2.03,1.99,1.92,1.87,2.01,3.99,3.68
372,E0,15/05/2016,Everton,Norwich,3,0,H,2,0,H,...,2.34,30,-0.75,1.95,1.92,2.00,1.93,1.74,4.38,4.60
373,E0,15/05/2016,Newcastle,Tottenham,5,1,H,2,0,H,...,2.21,30,0.75,1.94,1.89,2.01,1.97,5.30,4.18,1.69
374,E0,15/05/2016,Southampton,Crystal Palace,4,1,H,1,0,H,...,2.26,31,-1.50,2.00,1.93,1.98,1.92,1.29,6.80,10.00
375,E0,15/05/2016,Stoke,West Ham,2,1,H,0,1,A,...,2.27,30,0.25,2.11,2.03,1.87,1.83,3.05,4.00,2.26
376,E0,15/05/2016,Swansea,Man City,1,1,D,1,1,D,...,2.45,31,1.00,2.14,2.05,1.85,1.81,7.05,5.00,1.47
377,E0,15/05/2016,Watford,Sunderland,2,2,D,0,1,A,...,2.10,29,-0.50,2.06,2.01,1.91,1.85,1.64,4.52,5.27
378,E0,15/05/2016,West Brom,Liverpool,1,1,D,1,1,D,...,2.09,30,-0.25,2.10,2.05,1.86,1.81,2.61,3.75,2.70
379,E0,17/05/2016,Man United,Bournemouth,3,1,H,1,0,H,...,2.20,29,-0.75,1.88,1.84,2.08,2.02,1.50,4.60,7.03

In [41]:
df.shape

(380, 65)

In [42]:
print(df.columns)

Index(['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC',
       'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD',
       'BWA', 'IWH', 'IWD', 'IWA', 'LBH', 'LBD', 'LBA', 'PSH', 'PSD', 'PSA',
       'WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA', 'Bb1X2', 'BbMxH', 'BbAvH',
       'BbMxD', 'BbAvD', 'BbMxA', 'BbAvA', 'BbOU', 'BbMx>2.5', 'BbAv>2.5',
       'BbMx<2.5', 'BbAv<2.5', 'BbAH', 'BbAHh', 'BbMxAHH', 'BbAvAHH',
       'BbMxAHA', 'BbAvAHA', 'PSCH', 'PSCD', 'PSCA'],
      dtype='object')

# Project 2
**Column Name Rename**

In [43]:
df.rename(columns={'HomeTeam': 'home_team',
                   'AwayTeam': 'away_team'},inplace=True)

In [44]:
df.head(5)

,Div,Date,home_team,away_team,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,PSCH,PSCD,PSCA
0,E0,08/08/2015,Bournemouth,Aston Villa,0,1,A,0,0,D,...,1.79,26,-0.5,1.98,1.93,1.99,1.92,1.82,3.88,4.70
1,E0,08/08/2015,Chelsea,Swansea,2,2,D,2,1,H,...,1.99,27,-1.5,2.24,2.16,1.80,1.73,1.37,5.04,10.88
2,E0,08/08/2015,Everton,Watford,2,2,D,0,1,A,...,1.96,26,-1.0,2.28,2.18,1.76,1.71,1.75,3.76,5.44
3,E0,08/08/2015,Leicester,Sunderland,4,2,H,3,0,H,...,1.67,26,-0.5,2.00,1.95,1.96,1.90,1.79,3.74,5.10
4,E0,08/08/2015,Man United,Tottenham,1,0,H,1,0,H,...,2.01,26,-1.0,2.20,2.09,1.82,1.78,1.64,4.07,6.04

# Project 3
**Dynamic Link/URL Construction**

## https://football-data.co.uk/mmz4281/1516/E0.csv
## https://football-data.co.uk/mmz4281/1516/E1.csv
## https://football-data.co.uk/mmz4281/1516/E2.csv
## https://football-data.co.uk/mmz4281/1516/E3.csv

In [45]:
root = 'https://football-data.co.uk/mmz4281/'



## Link Structure:
### https://football-data.co.uk/mmz4281/ + 1516/ + E0 + .csv

In [46]:
leagues = ['E0', 'E1', 'E2', 'E3']

In [47]:
df_frames = []
for x in leagues:
   df = pd.read_csv(root + '1516/' + x + '.csv')
   df_frames.append(df)

In [48]:
df_frames[0]

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,PSCH,PSCD,PSCA
0,E0,08/08/2015,Bournemouth,Aston Villa,0,1,A,0,0,D,...,1.79,26,-0.50,1.98,1.93,1.99,1.92,1.82,3.88,4.70
1,E0,08/08/2015,Chelsea,Swansea,2,2,D,2,1,H,...,1.99,27,-1.50,2.24,2.16,1.80,1.73,1.37,5.04,10.88
2,E0,08/08/2015,Everton,Watford,2,2,D,0,1,A,...,1.96,26,-1.00,2.28,2.18,1.76,1.71,1.75,3.76,5.44
3,E0,08/08/2015,Leicester,Sunderland,4,2,H,3,0,H,...,1.67,26,-0.50,2.00,1.95,1.96,1.90,1.79,3.74,5.10
4,E0,08/08/2015,Man United,Tottenham,1,0,H,1,0,H,...,2.01,26,-1.00,2.20,2.09,1.82,1.78,1.64,4.07,6.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,15/05/2016,Stoke,West Ham,2,1,H,0,1,A,...,2.27,30,0.25,2.11,2.03,1.87,1.83,3.05,4.00,2.26
376,E0,15/05/2016,Swansea,Man City,1,1,D,1,1,D,...,2.45,31,1.00,2.14,2.05,1.85,1.81,7.05,5.00,1.47
377,E0,15/05/2016,Watford,Sunderland,2,2,D,0,1,A,...,2.10,29,-0.50,2.06,2.01,1.91,1.85,1.64,4.52,5.27
378,E0,15/05/2016,West Brom,Liverpool,1,1,D,1,1,D,...,2.09,30,-0.25,2.10,2.05,1.86,1.81,2.61,3.75,2.70
379,E0,17/05/2016,Man United,Bournemouth,3,1,H,1,0,H,...,2.20,29,-0.75,1.88,1.84,2.08,2.02,1.50,4.60,7.03

# Project 4:
**Loop Diye Multiple Season/League Load**
***Start with 15 to 20***
### https://football-data.co.uk/mmz4281/1516/E0.csv
### https://football-data.co.uk/mmz4281/1617/E0.csv
### https://football-data.co.uk/mmz4281/1718/E0.csv

In [49]:
root =  'https://football-data.co.uk/mmz4281/'

In [50]:
leagues = ['E0', 'E1', 'E2']
frames_pro4 = []

In [51]:
for league in leagues:
    for season in range(15, 21):
      df_pro4 = pd.read_csv(root + str(season) + str(season + 1) + '/' + league + '.csv')
      df_pro4.insert(1, 'season', season)
      frames_pro4.append(df_pro4)
df_master = pd.concat(frames_pro4)

In [52]:
df_master.shape

(8753, 128)

In [53]:
df_master.head()

,Div,season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,15,08/08/2015,Bournemouth,Aston Villa,0.0,1.0,A,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E0,15,08/08/2015,Chelsea,Swansea,2.0,2.0,D,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E0,15,08/08/2015,Everton,Watford,2.0,2.0,D,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E0,15,08/08/2015,Leicester,Sunderland,4.0,2.0,H,3.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E0,15,08/08/2015,Man United,Tottenham,1.0,0.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Project 5
## *Combining and Organizing Data in the Master Dictionary*

In [54]:
import pandas as pd

In [55]:
dict_league_name = {'Premier League': 'E0', 'Championship': 'E1', 'League 1': 'E2'}
print(dict_league_name['Premier League'])

E0

In [57]:
dict_concat_data = {}

for league in dict_league_name:
    frames = []
    for season in range(15, 21):
      df_pro4 = pd.read_csv(root + str(season) + str(season + 1) + '/' + dict_league_name[league] + '.csv')
      df_pro4.insert(1, 'season', season)
      frames.append(df_pro4)
    df_master = pd.concat(frames)
    dict_concat_data[league] = df_master

In [61]:
dict_concat_data['Championship']

,Div,season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E1,15,07/08/15,Brighton,Nott'm Forest,1,0,H,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E1,15,08/08/15,Birmingham,Reading,2,1,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E1,15,08/08/15,Blackburn,Wolves,1,2,A,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E1,15,08/08/15,Bolton,Derby,0,0,D,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E1,15,08/08/15,Brentford,Ipswich,2,2,D,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,E1,20,08/05/2021,Middlesbrough,Wycombe,0,3,A,0.0,2.0,...,2.06,-0.50,1.77,2.02,1.83,2.07,1.87,2.12,1.81,2.04
548,E1,20,08/05/2021,Nott'm Forest,Preston,1,2,A,1.0,0.0,...,1.77,-0.25,1.97,1.93,1.95,1.95,1.98,1.98,1.93,1.92
549,E1,20,08/05/2021,QPR,Luton,3,1,H,1.0,1.0,...,2.17,-0.25,1.95,1.95,1.96,1.94,1.98,2.02,1.90,1.95
550,E1,20,08/05/2021,Reading,Huddersfield,2,2,D,2.0,1.0,...,2.11,-0.50,1.85,2.05,1.86,2.05,1.88,2.08,1.84,2.01
551,E1,20,08/05/2021,Watford,Swansea,2,0,H,0.0,0.0,...,1.80,-0.25,2.08,1.82,2.07,1.85,2.14,1.90,2.04,1.82